# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  iOS-build:
    # The type of runner that the job will run on
    runs-on:  self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build iOS project
        run: |
            echo Making ios build
            
            xcodebuild -project DemoAppiOS.xcodeproj -scheme DemoAppiOS -sdk iphoneos14.4 clean analyze

            xcodebuild -workspace DemoAppiOS.xcworkspace -scheme DemoAppiOS  -destination generic/platform=iOS build

            xcodebuild -workspace DemoAppiOS.xcworkspace -scheme DemoAppiOS -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/DemoAppiOS.xcarchive

            xcodebuild -exportArchive -archivePath $PWD/build/DemoAppiOS.xcarchive -exportOptionsPlist demoAppiOS/info.plist -exportPath $PWD/build
            
            appPath=$(curl -u "vhvl_9KOMkx:puL2x1SZ4AhecfrcxW39" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@build/DemoAppiOS.ipa")

            echo $appPath

            browserStackAppPath=$(echo $appPath | jq --raw-output '.app_url')
            
            echo $browserStackAppPath
