# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  iOS-build:
    # The type of runner that the job will run on
    runs-on:  self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build iOS project
        run: |
            echo Making ios build
            
            xcodebuild -allowProvisioningUpdates
            
            xcodebuild -project DemoAppiOS.xcodeproj -scheme DemoAppiOS -sdk iphoneos14.4 clean analyze

            xcodebuild -workspace DemoAppiOS.xcworkspace -scheme DemoAppiOS  -destination generic/platform=iOS build

            xcodebuild -workspace DemoAppiOS.xcworkspace -scheme DemoAppiOS -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/DemoAppiOS.xcarchive

            xcodebuild -exportArchive -archivePath $PWD/build/DemoAppiOS.xcarchive -exportOptionsPlist demoAppiOS/info.plist -exportPath $PWD/build
            
  curl --location --request POST 'https://api.github.com/repos/vishuhanda/browserstacknewappium/dispatches' --header 'Accept: application/vnd.github.v3+json' --header 'Authorization: token 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' --header 'Content-Type: application/json' --data-raw '{"event_type": "triggermavenbuild","client_payload":{"abc":"bs://08760d3f8668615030d376a1f755544a4e027df3"}}'
